apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-crd-access
subjects:
- kind: ServiceAccount
  name: default
  namespace: sn-labs-virendraswam
roleRef:
  kind: ClusterRole
  name: cluster-admin  # This grants full cluster-wide access, adjust if necessary
  apiGroup: rbac.authorization.k8s.io
